# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assimilator.ui'
#
# Created: Sat Jun 21 13:58:54 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 590)
        MainWindow.setMinimumSize(QtCore.QSize(855, 590))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/1-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/1-48.ico"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/2-48.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/1-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/3-48.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/3-48.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/2-48.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/1-48.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(776, 551))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelBonjour = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBonjour.sizePolicy().hasHeightForWidth())
        self.labelBonjour.setSizePolicy(sizePolicy)
        self.labelBonjour.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBonjour.setFont(font)
        self.labelBonjour.setObjectName("labelBonjour")
        self.verticalLayout_8.addWidget(self.labelBonjour)
        self.labelExp = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelExp.setFont(font)
        self.labelExp.setObjectName("labelExp")
        self.verticalLayout_8.addWidget(self.labelExp)
        self.horizontalLayout_26.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelNiveau = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNiveau.setFont(font)
        self.labelNiveau.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelNiveau.setObjectName("labelNiveau")
        self.verticalLayout_9.addWidget(self.labelNiveau)
        self.labelIndex = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelIndex.setFont(font)
        self.labelIndex.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelIndex.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelIndex.setObjectName("labelIndex")
        self.verticalLayout_9.addWidget(self.labelIndex)
        self.horizontalLayout_26.addLayout(self.verticalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem3)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.MainStackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.MainStackedWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainStackedWidget.sizePolicy().hasHeightForWidth())
        self.MainStackedWidget.setSizePolicy(sizePolicy)
        self.MainStackedWidget.setMinimumSize(QtCore.QSize(758, 0))
        self.MainStackedWidget.setObjectName("MainStackedWidget")
        self.Menu = QtGui.QWidget()
        self.Menu.setObjectName("Menu")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Menu)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtGui.QWidget(self.Menu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.labelActivite = QtGui.QLabel(self.widget)
        self.labelActivite.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelActivite.sizePolicy().hasHeightForWidth())
        self.labelActivite.setSizePolicy(sizePolicy)
        self.labelActivite.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(24)
        self.labelActivite.setFont(font)
        self.labelActivite.setCursor(QtCore.Qt.ArrowCursor)
        self.labelActivite.setObjectName("labelActivite")
        self.horizontalLayout_20.addWidget(self.labelActivite)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        spacerItem5 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtGui.QSpacerItem(40, 9, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.toolButtonQCM = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonQCM.sizePolicy().hasHeightForWidth())
        self.toolButtonQCM.setSizePolicy(sizePolicy)
        self.toolButtonQCM.setMinimumSize(QtCore.QSize(150, 100))
        self.toolButtonQCM.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButtonQCM.setFont(font)
        self.toolButtonQCM.setCursor(QtCore.Qt.PointingHandCursor)
        self.toolButtonQCM.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/flags/toeic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonQCM.setIcon(icon1)
        self.toolButtonQCM.setIconSize(QtCore.QSize(150, 100))
        self.toolButtonQCM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonQCM.setAutoRaise(True)
        self.toolButtonQCM.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonQCM.setObjectName("toolButtonQCM")
        self.horizontalLayout.addWidget(self.toolButtonQCM)
        spacerItem7 = QtGui.QSpacerItem(40, 9, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.toolButtonTraduction = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonTraduction.sizePolicy().hasHeightForWidth())
        self.toolButtonTraduction.setSizePolicy(sizePolicy)
        self.toolButtonTraduction.setMinimumSize(QtCore.QSize(150, 100))
        self.toolButtonTraduction.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButtonTraduction.setFont(font)
        self.toolButtonTraduction.setCursor(QtCore.Qt.PointingHandCursor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/flags/qcm6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonTraduction.setIcon(icon2)
        self.toolButtonTraduction.setIconSize(QtCore.QSize(150, 100))
        self.toolButtonTraduction.setAutoRaise(True)
        self.toolButtonTraduction.setObjectName("toolButtonTraduction")
        self.horizontalLayout.addWidget(self.toolButtonTraduction)
        spacerItem8 = QtGui.QSpacerItem(40, 8, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.toolButtonCours = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonCours.sizePolicy().hasHeightForWidth())
        self.toolButtonCours.setSizePolicy(sizePolicy)
        self.toolButtonCours.setMinimumSize(QtCore.QSize(150, 100))
        self.toolButtonCours.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButtonCours.setFont(font)
        self.toolButtonCours.setCursor(QtCore.Qt.PointingHandCursor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/flags/traduct.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCours.setIcon(icon3)
        self.toolButtonCours.setIconSize(QtCore.QSize(150, 100))
        self.toolButtonCours.setAutoRepeatDelay(0)
        self.toolButtonCours.setAutoRepeatInterval(0)
        self.toolButtonCours.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButtonCours.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonCours.setAutoRaise(True)
        self.toolButtonCours.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonCours.setObjectName("toolButtonCours")
        self.horizontalLayout.addWidget(self.toolButtonCours)
        spacerItem9 = QtGui.QSpacerItem(40, 9, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem10 = QtGui.QSpacerItem(48, 9, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.progressBarQCM = QtGui.QProgressBar(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarQCM.sizePolicy().hasHeightForWidth())
        self.progressBarQCM.setSizePolicy(sizePolicy)
        self.progressBarQCM.setMinimumSize(QtCore.QSize(150, 20))
        self.progressBarQCM.setMaximumSize(QtCore.QSize(256, 20))
        self.progressBarQCM.setProperty("value", 0)
        self.progressBarQCM.setObjectName("progressBarQCM")
        self.horizontalLayout_2.addWidget(self.progressBarQCM)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.progressBarTraduction = QtGui.QProgressBar(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarTraduction.sizePolicy().hasHeightForWidth())
        self.progressBarTraduction.setSizePolicy(sizePolicy)
        self.progressBarTraduction.setMinimumSize(QtCore.QSize(150, 20))
        self.progressBarTraduction.setMaximumSize(QtCore.QSize(256, 20))
        self.progressBarTraduction.setProperty("value", 0)
        self.progressBarTraduction.setObjectName("progressBarTraduction")
        self.horizontalLayout_2.addWidget(self.progressBarTraduction)
        spacerItem12 = QtGui.QSpacerItem(40, 8, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.progressBarCours = QtGui.QProgressBar(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarCours.sizePolicy().hasHeightForWidth())
        self.progressBarCours.setSizePolicy(sizePolicy)
        self.progressBarCours.setMinimumSize(QtCore.QSize(150, 20))
        self.progressBarCours.setMaximumSize(QtCore.QSize(256, 20))
        self.progressBarCours.setProperty("value", 0)
        self.progressBarCours.setObjectName("progressBarCours")
        self.horizontalLayout_2.addWidget(self.progressBarCours)
        spacerItem13 = QtGui.QSpacerItem(40, 9, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem14 = QtGui.QSpacerItem(20, 150, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem14)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonProfil = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonProfil.sizePolicy().hasHeightForWidth())
        self.pushButtonProfil.setSizePolicy(sizePolicy)
        self.pushButtonProfil.setMaximumSize(QtCore.QSize(256, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonProfil.setFont(font)
        self.pushButtonProfil.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButtonProfil.setObjectName("pushButtonProfil")
        self.horizontalLayout_3.addWidget(self.pushButtonProfil)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.widget)
        self.MainStackedWidget.addWidget(self.Menu)
        self.MainQCM = QtGui.QWidget()
        self.MainQCM.setObjectName("MainQCM")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.MainQCM)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelQuestion = QtGui.QLabel(self.MainQCM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelQuestion.sizePolicy().hasHeightForWidth())
        self.labelQuestion.setSizePolicy(sizePolicy)
        self.labelQuestion.setMinimumSize(QtCore.QSize(750, 40))
        self.labelQuestion.setMaximumSize(QtCore.QSize(2000, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuestion.setObjectName("labelQuestion")
        self.verticalLayout_6.addWidget(self.labelQuestion)
        spacerItem15 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem15)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 2, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 2, 4, 1, 1)
        self.pushButtonRep4 = QtGui.QPushButton(self.MainQCM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRep4.sizePolicy().hasHeightForWidth())
        self.pushButtonRep4.setSizePolicy(sizePolicy)
        self.pushButtonRep4.setMinimumSize(QtCore.QSize(126, 80))
        self.pushButtonRep4.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRep4.setFont(font)
        self.pushButtonRep4.setObjectName("pushButtonRep4")
        self.gridLayout_3.addWidget(self.pushButtonRep4, 4, 3, 1, 1)
        self.pushButtonRep2 = QtGui.QPushButton(self.MainQCM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRep2.sizePolicy().hasHeightForWidth())
        self.pushButtonRep2.setSizePolicy(sizePolicy)
        self.pushButtonRep2.setMinimumSize(QtCore.QSize(126, 80))
        self.pushButtonRep2.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRep2.setFont(font)
        self.pushButtonRep2.setObjectName("pushButtonRep2")
        self.gridLayout_3.addWidget(self.pushButtonRep2, 2, 3, 1, 1)
        self.pushButtonRep3 = QtGui.QPushButton(self.MainQCM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRep3.sizePolicy().hasHeightForWidth())
        self.pushButtonRep3.setSizePolicy(sizePolicy)
        self.pushButtonRep3.setMinimumSize(QtCore.QSize(126, 80))
        self.pushButtonRep3.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRep3.setFont(font)
        self.pushButtonRep3.setObjectName("pushButtonRep3")
        self.gridLayout_3.addWidget(self.pushButtonRep3, 4, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(15, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 2, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(0, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem19, 3, 3, 1, 1)
        self.pushButtonRep1 = QtGui.QPushButton(self.MainQCM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRep1.sizePolicy().hasHeightForWidth())
        self.pushButtonRep1.setSizePolicy(sizePolicy)
        self.pushButtonRep1.setMinimumSize(QtCore.QSize(126, 80))
        self.pushButtonRep1.setMaximumSize(QtCore.QSize(256, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRep1.setFont(font)
        self.pushButtonRep1.setObjectName("pushButtonRep1")
        self.gridLayout_3.addWidget(self.pushButtonRep1, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        spacerItem20 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem20)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonCpa = QtGui.QPushButton(self.MainQCM)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCpa.sizePolicy().hasHeightForWidth())
        self.pushButtonCpa.setSizePolicy(sizePolicy)
        self.pushButtonCpa.setMinimumSize(QtCore.QSize(256, 40))
        self.pushButtonCpa.setMaximumSize(QtCore.QSize(256, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCpa.setFont(font)
        self.pushButtonCpa.setObjectName("pushButtonCpa")
        self.gridLayout_2.addWidget(self.pushButtonCpa, 0, 0, 1, 1)
        self.labelSpeak = QtGui.QLabel(self.MainQCM)
        self.labelSpeak.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSpeak.setFont(font)
        self.labelSpeak.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSpeak.setObjectName("labelSpeak")
        self.gridLayout_2.addWidget(self.labelSpeak, 2, 0, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem21, 3, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem22, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem23)
        self.progressBarQCM_2 = QtGui.QProgressBar(self.MainQCM)
        self.progressBarQCM_2.setMaximumSize(QtCore.QSize(500, 20))
        self.progressBarQCM_2.setProperty("value", 0)
        self.progressBarQCM_2.setObjectName("progressBarQCM_2")
        self.horizontalLayout_6.addWidget(self.progressBarQCM_2)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem24)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonBack = QtGui.QPushButton(self.MainQCM)
        self.pushButtonBack.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_7.addWidget(self.pushButtonBack)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.MainStackedWidget.addWidget(self.MainQCM)
        self.CoursSelec = QtGui.QWidget()
        self.CoursSelec.setObjectName("CoursSelec")
        self.verticalLayout = QtGui.QVBoxLayout(self.CoursSelec)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem25)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem26)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButtonHelp = QtGui.QPushButton(self.CoursSelec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonHelp.sizePolicy().hasHeightForWidth())
        self.pushButtonHelp.setSizePolicy(sizePolicy)
        self.pushButtonHelp.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonHelp.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButtonHelp.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButtonHelp.setObjectName("pushButtonHelp")
        self.verticalLayout_12.addWidget(self.pushButtonHelp)
        spacerItem27 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem27)
        self.labelTextPerso = QtGui.QLabel(self.CoursSelec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTextPerso.sizePolicy().hasHeightForWidth())
        self.labelTextPerso.setSizePolicy(sizePolicy)
        self.labelTextPerso.setMaximumSize(QtCore.QSize(2000, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTextPerso.setFont(font)
        self.labelTextPerso.setObjectName("labelTextPerso")
        self.verticalLayout_12.addWidget(self.labelTextPerso)
        spacerItem28 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem28)
        self.horizontalLayout_30.addLayout(self.verticalLayout_12)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem29)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem30)
        self.listSujet = QtGui.QListWidget(self.CoursSelec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listSujet.sizePolicy().hasHeightForWidth())
        self.listSujet.setSizePolicy(sizePolicy)
        self.listSujet.setMinimumSize(QtCore.QSize(200, 0))
        self.listSujet.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(15)
        self.listSujet.setFont(font)
        self.listSujet.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listSujet.setObjectName("listSujet")
        self.horizontalLayout_9.addWidget(self.listSujet)
        self.listChapter = QtGui.QListWidget(self.CoursSelec)
        self.listChapter.setMinimumSize(QtCore.QSize(276, 0))
        self.listChapter.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(15)
        self.listChapter.setFont(font)
        self.listChapter.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listChapter.setObjectName("listChapter")
        self.horizontalLayout_9.addWidget(self.listChapter)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem31)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem32)
        self.label_4 = QtGui.QLabel(self.CoursSelec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem33 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem33)
        self.pushButtonGo = QtGui.QPushButton(self.CoursSelec)
        self.pushButtonGo.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.verticalLayout_3.addWidget(self.pushButtonGo)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem34)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem35)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem36 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem36)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButtonBack3 = QtGui.QPushButton(self.CoursSelec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBack3.sizePolicy().hasHeightForWidth())
        self.pushButtonBack3.setSizePolicy(sizePolicy)
        self.pushButtonBack3.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack3.setFont(font)
        self.pushButtonBack3.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButtonBack3.setObjectName("pushButtonBack3")
        self.horizontalLayout_17.addWidget(self.pushButtonBack3)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.MainStackedWidget.addWidget(self.CoursSelec)
        self.Cours = QtGui.QWidget()
        self.Cours.setObjectName("Cours")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Cours)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem37 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem37)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem38)
        self.label_3 = QtGui.QLabel(self.Cours)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(2000, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_29.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_29)
        spacerItem39 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem39)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labelEnonceCours = QtGui.QLabel(self.Cours)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEnonceCours.sizePolicy().hasHeightForWidth())
        self.labelEnonceCours.setSizePolicy(sizePolicy)
        self.labelEnonceCours.setMinimumSize(QtCore.QSize(100, 0))
        self.labelEnonceCours.setMaximumSize(QtCore.QSize(2000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(48)
        self.labelEnonceCours.setFont(font)
        self.labelEnonceCours.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEnonceCours.setObjectName("labelEnonceCours")
        self.horizontalLayout_13.addWidget(self.labelEnonceCours)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        spacerItem40 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem40)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEditCours = QtGui.QLineEdit(self.Cours)
        self.lineEditCours.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEditCours.setFont(font)
        self.lineEditCours.setObjectName("lineEditCours")
        self.horizontalLayout_19.addWidget(self.lineEditCours)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        spacerItem41 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem41)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButtonValideCours = QtGui.QPushButton(self.Cours)
        self.pushButtonValideCours.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonValideCours.setFont(font)
        self.pushButtonValideCours.setObjectName("pushButtonValideCours")
        self.horizontalLayout_24.addWidget(self.pushButtonValideCours)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButtonCpa3 = QtGui.QPushButton(self.Cours)
        self.pushButtonCpa3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonCpa3.setFont(font)
        self.pushButtonCpa3.setObjectName("pushButtonCpa3")
        self.horizontalLayout_21.addWidget(self.pushButtonCpa3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.labelValiditeCours = QtGui.QLabel(self.Cours)
        self.labelValiditeCours.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelValiditeCours.setFont(font)
        self.labelValiditeCours.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValiditeCours.setObjectName("labelValiditeCours")
        self.horizontalLayout_23.addWidget(self.labelValiditeCours)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        spacerItem42 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem42)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButtonBack4 = QtGui.QPushButton(self.Cours)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBack4.sizePolicy().hasHeightForWidth())
        self.pushButtonBack4.setSizePolicy(sizePolicy)
        self.pushButtonBack4.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButtonBack4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack4.setFont(font)
        self.pushButtonBack4.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButtonBack4.setObjectName("pushButtonBack4")
        self.horizontalLayout_18.addWidget(self.pushButtonBack4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.MainStackedWidget.addWidget(self.Cours)
        self.gridLayout.addWidget(self.MainStackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuChapitre = QtGui.QMenu(self.menubar)
        self.menuChapitre.setObjectName("menuChapitre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionA_propos = QtGui.QAction(MainWindow)
        self.actionA_propos.setObjectName("actionA_propos")
        self.actionChange_level = QtGui.QAction(MainWindow)
        self.actionChange_level.setObjectName("actionChange_level")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionImporter = QtGui.QAction(MainWindow)
        self.actionImporter.setObjectName("actionImporter")
        self.actionExporter = QtGui.QAction(MainWindow)
        self.actionExporter.setObjectName("actionExporter")
        self.actionR_initialiser = QtGui.QAction(MainWindow)
        self.actionR_initialiser.setObjectName("actionR_initialiser")
        self.menuFile.addAction(self.actionQuitter)
        self.menuFile.addAction(self.actionImporter)
        self.menuFile.addAction(self.actionExporter)
        self.menu.addAction(self.actionA_propos)
        self.menuEdit.addAction(self.actionChange_level)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuChapitre.addAction(self.actionR_initialiser)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuChapitre.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.labelBonjour.setBuddy(self.MainStackedWidget)

        self.retranslateUi(MainWindow)
        self.MainStackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuitter, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionA_propos, QtCore.SIGNAL("triggered()"), self.pushButtonHelp.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Assimilation Learning Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBonjour.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bonjour </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelExp.setText(QtGui.QApplication.translate("MainWindow", "T\'es un winner : /", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNiveau.setText(QtGui.QApplication.translate("MainWindow", "Niveau : Débutant", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIndex.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sujet : Chapter</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelActivite.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Unicode MS\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#4f4f4f;\">Veuillez choisir une activité</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonQCM.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Questionnaire à choix multiples.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Entrainement au TOEIC</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonQCM.setText(QtGui.QApplication.translate("MainWindow", "TOEIC", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonTraduction.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Intégrez vos propres QCM pour apprendre plus facilement !</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonTraduction.setText(QtGui.QApplication.translate("MainWindow", "QCM", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCours.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Intégrez vos propres cours et listes de vocabulaires !</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonCours.setText(QtGui.QApplication.translate("MainWindow", "Traduction", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonProfil.setText(QtGui.QApplication.translate("MainWindow", "Changer de profil", None, QtGui.QApplication.UnicodeUTF8))
        self.labelQuestion.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Question ?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRep4.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRep2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRep3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRep1.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCpa.setText(QtGui.QApplication.translate("MainWindow", "Je ne sais pas", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSpeak.setText(QtGui.QApplication.translate("MainWindow", "Allez vasy", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBack.setText(QtGui.QApplication.translate("MainWindow", "Retour au menu", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHelp.setText(QtGui.QApplication.translate("MainWindow", "Ajouter une nouvelle liste", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTextPerso.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ici vous pouvez sélectionner vos listes d\'apprentissage personnalisées :</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Valider</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGo.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBack3.setText(QtGui.QApplication.translate("MainWindow", "Retour au menu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Traduire le mot suivant :</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEnonceCours.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Unicode MS\'; font-size:48pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditCours.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Appuyer sur entrée pour valider</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonValideCours.setText(QtGui.QApplication.translate("MainWindow", "Valider", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCpa3.setText(QtGui.QApplication.translate("MainWindow", "Je ne sais pas", None, QtGui.QApplication.UnicodeUTF8))
        self.labelValiditeCours.setText(QtGui.QApplication.translate("MainWindow", "Allez vas-y !", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBack4.setText(QtGui.QApplication.translate("MainWindow", "Retour", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChapitre.setTitle(QtGui.QApplication.translate("MainWindow", "Chapitre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA_propos.setText(QtGui.QApplication.translate("MainWindow", "À propos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_level.setText(QtGui.QApplication.translate("MainWindow", "Change level", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImporter.setText(QtGui.QApplication.translate("MainWindow", "Importer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExporter.setText(QtGui.QApplication.translate("MainWindow", "Exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionR_initialiser.setText(QtGui.QApplication.translate("MainWindow", "Réinitialiser", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
