# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Preferences.ui'
#
# Created: Sat Jun 21 13:59:05 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PreferenceWindow(object):
    def setupUi(self, PreferenceWindow):
        PreferenceWindow.setObjectName("PreferenceWindow")
        PreferenceWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        PreferenceWindow.resize(585, 234)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreferenceWindow.sizePolicy().hasHeightForWidth())
        PreferenceWindow.setSizePolicy(sizePolicy)
        PreferenceWindow.setMinimumSize(QtCore.QSize(585, 234))
        PreferenceWindow.setMaximumSize(QtCore.QSize(585, 234))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PreferenceWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(PreferenceWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelSelect = QtGui.QLabel(PreferenceWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSelect.sizePolicy().hasHeightForWidth())
        self.labelSelect.setSizePolicy(sizePolicy)
        self.labelSelect.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSelect.setObjectName("labelSelect")
        self.horizontalLayout_5.addWidget(self.labelSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtGui.QSpacerItem(60, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.checkBoxAccents = QtGui.QCheckBox(PreferenceWindow)
        self.checkBoxAccents.setObjectName("checkBoxAccents")
        self.horizontalLayout_7.addWidget(self.checkBoxAccents)
        self.checkBoxLiaison = QtGui.QCheckBox(PreferenceWindow)
        self.checkBoxLiaison.setObjectName("checkBoxLiaison")
        self.horizontalLayout_7.addWidget(self.checkBoxLiaison)
        self.checkBoxPluriel = QtGui.QCheckBox(PreferenceWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxPluriel.sizePolicy().hasHeightForWidth())
        self.checkBoxPluriel.setSizePolicy(sizePolicy)
        self.checkBoxPluriel.setObjectName("checkBoxPluriel")
        self.horizontalLayout_7.addWidget(self.checkBoxPluriel)
        self.checkBoxDesordre = QtGui.QCheckBox(PreferenceWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxDesordre.sizePolicy().hasHeightForWidth())
        self.checkBoxDesordre.setSizePolicy(sizePolicy)
        self.checkBoxDesordre.setObjectName("checkBoxDesordre")
        self.horizontalLayout_7.addWidget(self.checkBoxDesordre)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(PreferenceWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxLevel = QtGui.QComboBox(PreferenceWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxLevel.sizePolicy().hasHeightForWidth())
        self.comboBoxLevel.setSizePolicy(sizePolicy)
        self.comboBoxLevel.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBoxLevel.setObjectName("comboBoxLevel")
        self.horizontalLayout.addWidget(self.comboBoxLevel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtGui.QLabel(PreferenceWindow)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.lcdNumber = QtGui.QLCDNumber(PreferenceWindow)
        self.lcdNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lcdNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_6.addWidget(self.lcdNumber)
        self.labelPercent = QtGui.QLabel(PreferenceWindow)
        self.labelPercent.setObjectName("labelPercent")
        self.horizontalLayout_6.addWidget(self.labelPercent)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalSlider = QtGui.QSlider(PreferenceWindow)
        self.horizontalSlider.setMaximum(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButtonOK = QtGui.QPushButton(PreferenceWindow)
        self.pushButtonOK.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonOK.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_2.addWidget(self.pushButtonOK)
        self.pushButtonAnnuler = QtGui.QPushButton(PreferenceWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAnnuler.sizePolicy().hasHeightForWidth())
        self.pushButtonAnnuler.setSizePolicy(sizePolicy)
        self.pushButtonAnnuler.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonAnnuler.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonAnnuler.setObjectName("pushButtonAnnuler")
        self.horizontalLayout_2.addWidget(self.pushButtonAnnuler)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PreferenceWindow)
        QtCore.QMetaObject.connectSlotsByName(PreferenceWindow)

    def retranslateUi(self, PreferenceWindow):
        PreferenceWindow.setWindowTitle(QtGui.QApplication.translate("PreferenceWindow", "Édition des préférences du profil utilisateur", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelect.setText(QtGui.QApplication.translate("PreferenceWindow", "Choisissez les exceptions de notation : (exemple : si vous cochez \"accents\", les mots mal accentués seront acceptés)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAccents.setText(QtGui.QApplication.translate("PreferenceWindow", "accents", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLiaison.setText(QtGui.QApplication.translate("PreferenceWindow", "liaisons (tirets, apostrophes etc...)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxPluriel.setText(QtGui.QApplication.translate("PreferenceWindow", "pluriel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDesordre.setText(QtGui.QApplication.translate("PreferenceWindow", "ordre", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferenceWindow", "Modifier le niveau du chapitre en cours", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreferenceWindow", "Taux d\'erreur accepté ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPercent.setText(QtGui.QApplication.translate("PreferenceWindow", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOK.setText(QtGui.QApplication.translate("PreferenceWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAnnuler.setText(QtGui.QApplication.translate("PreferenceWindow", "Annuler", None, QtGui.QApplication.UnicodeUTF8))

import resPref_rc
