# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserWindow.ui'
#
# Created: Sat Jul 12 12:47:10 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        UserWindow.resize(540, 250)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UserWindow.sizePolicy().hasHeightForWidth())
        UserWindow.setSizePolicy(sizePolicy)
        UserWindow.setMinimumSize(QtCore.QSize(540, 180))
        UserWindow.setMaximumSize(QtCore.QSize(540, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(UserWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelSelect = QtGui.QLabel(UserWindow)
        self.labelSelect.setObjectName("labelSelect")
        self.verticalLayout.addWidget(self.labelSelect)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(UserWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxAccount = QtGui.QComboBox(UserWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxAccount.sizePolicy().hasHeightForWidth())
        self.comboBoxAccount.setSizePolicy(sizePolicy)
        self.comboBoxAccount.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBoxAccount.setObjectName("comboBoxAccount")
        self.horizontalLayout.addWidget(self.comboBoxAccount)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEditNewName = QtGui.QLineEdit(UserWindow)
        self.lineEditNewName.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNewName.sizePolicy().hasHeightForWidth())
        self.lineEditNewName.setSizePolicy(sizePolicy)
        self.lineEditNewName.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEditNewName.setObjectName("lineEditNewName")
        self.horizontalLayout.addWidget(self.lineEditNewName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonOK = QtGui.QPushButton(UserWindow)
        self.pushButtonOK.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout_2.addWidget(self.pushButtonOK)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButtonOption = QtGui.QPushButton(UserWindow)
        self.pushButtonOption.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonOption.setObjectName("pushButtonOption")
        self.horizontalLayout_2.addWidget(self.pushButtonOption)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonDelete = QtGui.QPushButton(UserWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDelete.sizePolicy().hasHeightForWidth())
        self.pushButtonDelete.setSizePolicy(sizePolicy)
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_5.addWidget(self.pushButtonDelete)
        self.pushButtonExport = QtGui.QPushButton(UserWindow)
        self.pushButtonExport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.horizontalLayout_5.addWidget(self.pushButtonExport)
        self.pushButtonImport = QtGui.QPushButton(UserWindow)
        self.pushButtonImport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.horizontalLayout_5.addWidget(self.pushButtonImport)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(UserWindow)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        UserWindow.setWindowTitle(QtGui.QApplication.translate("UserWindow", "Sélectionner un compte", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSelect.setText(QtGui.QApplication.translate("UserWindow", "Sélectionner ou créer un nouveau compte pour continuer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UserWindow", "Choisir dans la liste", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOK.setText(QtGui.QApplication.translate("UserWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOption.setText(QtGui.QApplication.translate("UserWindow", "Options >>>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelete.setText(QtGui.QApplication.translate("UserWindow", "Supprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonExport.setText(QtGui.QApplication.translate("UserWindow", "Exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonImport.setText(QtGui.QApplication.translate("UserWindow", "Importer", None, QtGui.QApplication.UnicodeUTF8))

import resUsr_rc
